'use client';

import React, { useState } from 'react';
import { 
  BrainCircuit, 
  X, 
  Sparkles, 
  Lightbulb, 
  HelpCircle, 
  AlertTriangle, 
  Video, 
  FileText, 
  Copy, 
  Check, 
  Smile, 
  Flame,
  ThumbsUp
} from 'lucide-react';
import { VideoCommentSummary } from '@/lib/gemini';

interface CommentSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary: VideoCommentSummary | null;
  loading: boolean;
  videoTitle?: string;
}

export default function CommentSummaryModal({
  isOpen,
  onClose,
  summary,
  loading,
  videoTitle = 'Recent YouTube Video'
}: CommentSummaryModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    if (!summary) return;
    const textToCopy = `
📊 AI Video Comment Summary & Key Insights:
Video: "${videoTitle}"
Overview: ${summary.headline}

💡 Main Audience Talking Points:
${summary.mainPoints.map((p, i) => `${i + 1}. ${p}`).join('\n')}

❓ Top Student Doubts & Questions:
${summary.topDoubts.map((d, i) => `${i + 1}. ${d}`).join('\n')}

🚨 Viewer Issues & Constructive Feedback:
${summary.feedbackAndIssues.map((f, i) => `${i + 1}. ${f}`).join('\n')}

🚀 Next Video Content Demand:
${summary.nextContentIdeas.map((idea, i) => `${i + 1}. ${idea}`).join('\n')}

Generated by SW Tech Solution (Google Gemma 4 AI)
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-zinc-950 border border-zinc-800 rounded-3xl max-w-3xl w-full p-5 sm:p-7 relative shadow-2xl my-auto max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 pb-4 border-b border-zinc-800 shrink-0">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs font-bold mb-2">
              <BrainCircuit className="w-3.5 h-3.5 text-rose-400 animate-pulse" />
              Google Gemma 4 31B IT Thinking AI Insights
            </div>
            <h3 className="text-lg sm:text-xl font-extrabold text-white flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-amber-400" />
              Video Comments Summary & Audience Intelligence
            </h3>
            <p className="text-xs text-zinc-400 mt-1 truncate max-w-lg">
              Video: <span className="text-zinc-200 font-semibold">{videoTitle}</span>
            </p>
          </div>

          <button
            onClick={onClose}
            className="text-zinc-400 hover:text-white p-1.5 rounded-xl hover:bg-zinc-900 transition-all shrink-0"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="overflow-y-auto py-5 space-y-6 flex-1 pr-1 custom-scrollbar">
          {loading ? (
            <div className="py-16 text-center space-y-4">
              <div className="w-16 h-16 rounded-3xl bg-rose-600/10 text-rose-500 border border-rose-500/20 flex items-center justify-center mx-auto animate-spin">
                <Sparkles className="w-8 h-8" />
              </div>
              <h4 className="text-base font-bold text-white">Google Gemma 4 AI is Thinking...</h4>
              <p className="text-xs text-zinc-400 max-w-sm mx-auto">
                Reading all audience comments, extracting main discussion points, categorizing student doubts, and identifying next video demands.
              </p>
            </div>
          ) : summary ? (
            <>
              {/* Executive Headline & Sentiment */}
              <div className="p-5 rounded-2xl bg-gradient-to-r from-rose-950/30 via-zinc-900 to-zinc-950 border border-rose-500/30 shadow-lg">
                <span className="text-[10px] font-bold text-rose-400 uppercase tracking-wider block mb-1">
                  Executive Summary Overview ({summary.totalAnalyzed} Comments Analyzed)
                </span>
                <p className="text-sm sm:text-base font-bold text-white leading-snug">
                  "{summary.headline}"
                </p>

                {/* Sentiment Meter */}
                <div className="mt-4 pt-3 border-t border-zinc-800/80 flex flex-wrap items-center gap-4 text-xs font-semibold">
                  <span className="text-zinc-400 flex items-center gap-1.5">
                    <Smile className="w-4 h-4 text-emerald-400" />
                    Positive / Praise: <strong className="text-emerald-400">{summary.sentimentBreakdown?.positive || 80}%</strong>
                  </span>
                  <span className="text-zinc-400 flex items-center gap-1.5">
                    <HelpCircle className="w-4 h-4 text-amber-400" />
                    Doubts / Questions: <strong className="text-amber-400">{summary.sentimentBreakdown?.doubts || 15}%</strong>
                  </span>
                  <span className="text-zinc-400 flex items-center gap-1.5">
                    <AlertTriangle className="w-4 h-4 text-rose-400" />
                    Feedback / Complaints: <strong className="text-rose-400">{summary.sentimentBreakdown?.feedback || 5}%</strong>
                  </span>
                </div>
              </div>

              {/* 1. Main Points / Audience Talking Points */}
              {summary.mainPoints && summary.mainPoints.length > 0 && (
                <div className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
                    <Lightbulb className="w-4 h-4 text-amber-400" />
                    💡 Core Audience Talking Points & Reactions
                  </h4>
                  <ul className="space-y-2 text-xs text-zinc-200">
                    {summary.mainPoints.map((pt, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                        <span className="leading-relaxed">{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 2. Top Student Doubts & Questions */}
              {summary.topDoubts && summary.topDoubts.length > 0 && (
                <div className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
                    <HelpCircle className="w-4 h-4 text-rose-400" />
                    ❓ Top Student Doubts & FAQs
                  </h4>
                  <ul className="space-y-2.5 text-xs text-zinc-200">
                    {summary.topDoubts.map((doubt, i) => (
                      <li key={i} className="flex items-start gap-2.5 bg-zinc-950/60 p-2.5 rounded-xl border border-zinc-800/80">
                        <span className="font-bold text-rose-400 shrink-0">Q{i + 1}.</span>
                        <span className="leading-relaxed">{doubt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 3. Next Video Demand / Content Ideas */}
              {summary.nextContentIdeas && summary.nextContentIdeas.length > 0 && (
                <div className="p-5 rounded-2xl bg-gradient-to-r from-emerald-950/30 via-zinc-900 to-zinc-950 border border-emerald-500/30">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-3">
                    <Video className="w-4 h-4 text-emerald-400" />
                    🚀 High-Demand Next Video Ideas (What Audience Wants Next)
                  </h4>
                  <ul className="space-y-2 text-xs text-emerald-200">
                    {summary.nextContentIdeas.map((idea, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="font-bold text-emerald-400 shrink-0">#{i + 1}</span>
                        <span className="leading-relaxed">{idea}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 4. Feedback & Issues Reported */}
              {summary.feedbackAndIssues && summary.feedbackAndIssues.length > 0 && (
                <div className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800">
                  <h4 className="text-sm font-bold text-white flex items-center gap-2 mb-2">
                    <AlertTriangle className="w-4 h-4 text-amber-400" />
                    🚨 Issues & Constructive Feedback Reported
                  </h4>
                  <ul className="space-y-2 text-xs text-zinc-300">
                    {summary.feedbackAndIssues.map((item, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 shrink-0" />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          ) : (
            <div className="py-12 text-center text-xs text-zinc-400">
              No comments available to summarize.
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="pt-4 border-t border-zinc-800 flex items-center justify-between gap-4 shrink-0">
          <button
            onClick={handleCopy}
            disabled={!summary || loading}
            className="px-4 py-2.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-200 text-xs font-semibold flex items-center gap-2 transition-all disabled:opacity-50"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400 font-bold">Summary Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Summary & Insights</span>
              </>
            )}
          </button>

          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold transition-all"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
